version: '3.9'
services:
  redis:
    container_name: ${REDIS_SERVICE_NAME}
    image: ${REDIS_IMAGE}
    restart: always
    hostname: 'redis'
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  redisinsight:
    container_name: ${REDIS_MANAGE_SERVICE_NAME}
    image: ${REDIS_MANAGE_IMAGE}
    restart: always
    ports:
      - ${REDIS_MANAGE_PORT}:${REDIS_MANAGE_PORT}
    volumes:
      - ./data/redisinsight:/db
